stages:
- test
- build
- release

python2:
  image: python:2.7
  stage: test
  script:
  - apt-get update  && apt-get install -y python-gtk2 python-cairo python-gobject
  - ln -s /usr/lib/python2.7/dist-packages/gtk-2.0/ /usr/local/lib/python2.7/
  - ln -s /usr/lib/python2.7/dist-packages/cairo/ /usr/local/lib/python2.7/
  - ln -s /usr/lib/python2.7/dist-packages/pygtk.py /usr/local/lib/python2.7/
  - ln -s /usr/lib/python2.7/dist-packages/pygtk.pth /usr/local/lib/python2.7/
  - pip install tox
  - tox -e py27


# python34:
#  image: python:3.4
#  stage: test
#  script:
#  - apt-get update  && apt-get install -y python3-gi python3-cairo
#  - ln -s /usr/lib/python3/dist-packages/gi/ /usr/local/lib/python3/
#  - ln -s /usr/lib/python3/dist-packages/cairo/ /usr/local/lib/python3/
#  - pip install tox
#  - tox -e py34

# python35:
#  image: python:3.5
#  stage: test
#  script:
#  - apt-get update  && apt-get install -y python3-gi python3-cairo
#  - ln -s /usr/lib/python3/dist-packages/gi/ /usr/local/lib/python3/
#  - ln -s /usr/lib/python3/dist-packages/cairo/ /usr/local/lib/python3/
#  - pip install tox
#  - tox -e py35

# python36:
#  image: python:3.6
#  stage: test
#  script:
#  - apt-get update  && apt-get install -y python3-gi python3-cairo
#  - ln -s /usr/lib/python3/dist-packages/gi/ /usr/local/lib/python3/
#  - ln -s /usr/lib/python3/dist-packages/cairo/ /usr/local/lib/python3/
#  - pip install tox
#  - tox -e py36

pages:
  image: alpine
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - sphinx-build -b html docs/ _build/html/
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master