image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - sphinx-build -b html docs/ _build/
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
