repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: master
  hooks:
  - id: mypy
    rev: 0.730
    args: [ --warn-unused-configs ]
