trigger:
  branches:
    include:
      - '*'
      - refs/tags/*

variables:
  System.Debug: true

jobs:
  - job: Lint
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'

      - script: |
          pip install pre-commit
          pre-commit install-hooks
          pre-commit run --all-files

  - job: Windows
    dependsOn: Lint
    condition: succeeded()
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    variables:
      MSYSTEM: MINGW64
      MSYS2_ARCH: x86_64

    steps:
      - script: |
          choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
        displayName: Install MSYS2

      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
        displayName: Update MSYS2

      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-install.sh"
        displayName: Install Dependencies
        env:
          MSYS2_ARCH: $(MSYS2_ARCH)
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes

      - bash: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc ".azure/msys2-test.sh"
        displayName: Run Tests
        env:
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes

      - task: PublishTestResults@2
        condition: not(canceled())
        inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: Publish Test Results

      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc "win-installer/build-installer.sh"
        displayName: Create Windows Binaries
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
        env:
          MSYSTEM: $(MSYSTEM)
          CHERE_INVOKING: yes

      - task: CopyFiles@2
        displayName: Copy Windows Binaries
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          sourceFolder: 'win-installer'
          contents: '*.exe'
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: GitHubRelease@0
        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
        displayName: Create GitHub Release
        inputs:
          gitHubConnection: GaphorConnection
          repositoryName: gaphor/gaphor
          action: create
          tagSource: auto
          target: $(Build.SourceVersion)
          assets: $(Build.ArtifactStagingDirectory)/*.exe
          isDraft: true

  - job: macOS
    dependsOn: Lint
    condition: succeeded()
    pool:
      vmImage: 'macOS-10.13'
    timeoutInMinutes: 60
    variables:
        PKG_CONFIG_PATH: /usr/local/Cellar/libffi/3.2.1/lib/pkgconfig:${PKG_CONFIG_PATH:-}
    steps:
    - script: |
        brew install gobject-introspection gtk+3 adwaita-icon-theme
        source venv
        pip install pytest-xvfb
      displayName: 'Install dependencies'

    - script: |
        source venv
        pytest
      displayName: 'PyTest'
      env:
        PYTEST_ADDOPTS: "--doctest-modules --junitxml=junit/test-results.xml"

    - script: |
        cd macos-dmg
        ./package.sh
      displayName: Create macOS Package

    - task: CopyFiles@2
      displayName: Copy macOS Package
      inputs:
        sourceFolder: macos-dmg
        contents: '*.dmg'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: GitHubRelease@0
      condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
      displayName: Create GitHub Release
      inputs:
        gitHubConnection: GaphorConnection
        repositoryName: gaphor/gaphor
        action: create
        tagSource: auto
        target: $(Build.SourceVersion)
        assets: $(Build.ArtifactStagingDirectory)/*.dmg
        isDraft: true

  - job: Linux
    dependsOn: Lint
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 60

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: >
        sudo apt-get update -q && sudo apt-get install --no-install-recommends -y
        python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
      displayName: Install Ubuntu Dependencies

    - script: |
        source venv
      displayName: Install Python Dependencies

    - script: |
        mkdir -p /home/vsts/.local/share # This can be removed once we merge back to master (config dir)
        source venv
        xvfb-run pytest
      displayName: 'PyTest'
      env:
        PYTEST_ADDOPTS: "--doctest-modules --junitxml=junit/test-results.xml"


    - task: PublishTestResults@2
      condition: not(canceled())
      inputs:
        testResultsFiles: junit/test-results.xml
        testRunTitle: Publish Test Results

    - script: |
        source venv
        poetry build
      displayName: Build Wheel
    
    - script: |
        poetry config repositories.azure https://pkgs.dev.azure.com/gaphor-dev/_packaging/PyPI-Feed/pypi/upload
        poetry config http-basic.azure $(username) $(password)
        poetry publish -r azure
        exit 0
      displayName: Publish software
