name: 'gvsbuild'
description: 'Build GTK with gvsbuild or collect from cache if current'
outputs:
  cachekey:
    description: 'Cache key for checking if the cache is current'
    value: ${{ steps.cache-key-generator.outputs.cachekey }}
runs:
  using: composite
  steps:
    # Temporarily move the preinstalled git, it causes errors related to cygwin.
    - name: GTK binaries move git binary
      run: move "C:\Program Files\Git\usr\bin" "C:\Program Files\Git\usr\notbin"
      shell: cmd
    - name: GTK binaries run gvsbuild
      working-directory: gvsbuild
      run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 --enable-gi --py-wheel --gtk3-ver=3.24 gobject-introspection gtk3 pycairo pygobject adwaita-icon-theme hicolor-icon-theme
      shell: cmd
    - name: Copy wheels to cached directory
      run: Get-ChildItem C:\gtk-build\build\x64\release\*\dist\*.whl | ForEach-Object -process { cp $_ C:\gtk-build\gtk\x64\release\ }
      shell: PowerShell
    - name: GTK binaries restore git binary
      run: move "C:\Program Files\Git\usr\notbin" "C:\Program Files\Git\usr\bin"
      shell: cmd
