name: 'Create macOS Application'
description: 'Create and Sign macOS Application Using PyInstaller'
inputs:
  version:
    description: 'Gaphor version number'
    required: true
  base64_encoded_p12:
    description: 'base64_encoded_p12'
    required: true
  certpassword_p12:
    description: 'certpassword_p12'
    required: true
  ac_username:
    description: 'ac_usernmame'
    required: true
  ac_password:
    description: 'ac_password'
    required: true
  github_token:
    description: 'GitHub token for uploading releases'
    required: true
  mainline_build:
    description: 'Build is performed on the main line'
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Install Build Dependencies
      run: poetry install --no-dev --extras poethepoet
    - name: Build Wheel
      run: poetry run poe dist
    - name: Import codesign certificate
      uses: apple-actions/import-codesign-certs@v1.0.4
      with:
        p12-file-base64: ${{ inputs.base64_encoded_p12 }}
        p12-password: ${{ inputs.certpassword_p12 }}
    - name: Create Signed macOS Application
      run: poetry run poe package
    - name: Notarize app
      uses: devbotsxyz/xcode-notarize@v1.0.0
      with:
        product-path: "_packaging/dist/Gaphor.app"
        appstore-connect-username: ${{ inputs.ac_username }}
        appstore-connect-password: ${{ inputs.ac_password }}
    - name: Staple app
      uses: devbotsxyz/xcode-staple@v1.0.0
      with:
        product-path: "_packaging/dist/Gaphor.app"
    - name: Create dmg
      run: >
        cd _packaging

        create-dmg --volname "Gaphor ${{ inputs.version }}"
        --background "macos/background.png"
        --window-pos 200 120 --window-size 700 400 --icon-size 100
        --icon "Gaphor.app" 200 240 --hide-extension "Gaphor.app"
        --app-drop-link 500 240 "dist/Gaphor-${{ inputs.version }}.dmg"
        "dist/Gaphor.app"
    - name: Notarize dmg
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: "_packaging/dist/Gaphor-${{ inputs.version }}.dmg"
        appstore-connect-username: ${{ inputs.ac_username }}
        appstore-connect-password: ${{ inputs.ac_password }}
        primary-bundle-id: org.gaphor.gaphor
    - name: Staple .dmg
      uses: devbotsxyz/xcode-staple@v1.0.0
      with:
        product-path: "_packaging/dist/Gaphor-${{ inputs.version }}.dmg"
    - name: Upload Gaphor-${{ inputs.version }}.dmg
      uses: actions/upload-artifact@v3
      with:
        name: Gaphor-${{ inputs.version }}.dmg
        path: _packaging/dist/Gaphor-${{ inputs.version }}.dmg
    - name: Upload Assets (release only)
      uses: AButler/upload-release-assets@v2.0
      if: github.event_name == 'release'
      with:
        files: "_packaging/dist/Gaphor-${{ inputs.version }}.dmg"
        repo-token: ${{ inputs.github_token }}
