name: 'Install Dependencies and Test'
description: 'Collects project metadata, installs Python and Poetry, runs pytest'
outputs:
  version:
    description: 'Build version with added dev reference for non-releases'
    value: ${{ steps.meta.outputs.version }}
runs:
  using: composite
  steps:
    - name: Install Poetry
      run: pip install poetry==1.2.2
      shell: bash
    - name: Configure Poetry
      run: poetry config virtualenvs.in-project true
      shell: bash
    - name: Collect Project Data
      id: meta
      run: .github/scripts/metadata.sh
      shell: bash
    - name: Install Python Dependencies
      run: poetry install --no-interaction
      shell: bash
    - name: Compile translations
      run: poetry run poe gettext-mo
      shell: bash
    - name: Test with Pytest
      run: ${{ runner.os == 'Linux' && 'xvfb-run' || '' }} poetry run pytest --cov=gaphor
      shell: bash
