name: Docker
on:
  schedule:
    - cron: '15 1 * * 1' # Weekly at 01:15 UTC
  push:
    branches:
      - 'docker/**'
env:
  python_version: '3.10'
  registry: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: ${{ env.python_version }}
      - name: Lint with Pre-commit
        uses: pre-commit/action@v2.0.3
      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Poetry
        run: pip install poetry==1.1.12
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install Build Dependencies
        run: poetry install --no-dev --extras poethepoet
      - name: Build and Push
        run: |
          poetry run poe docker-build
          poetry run poe docker-push
