name: Release

on:
  release:
    types: [created, edited]

jobs:
  upload-windows:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
      MSYS2_ARCH: x86_64
    steps:
      - uses: actions/checkout@v1
      - name: Install MSYS2
        run: |
          choco install --no-progress msys2 --params="/NoUpdate /NoPath"
      - name: Update MSYS2
        run: |
          $env:PATH = "C:\tools\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem"
          C:\tools\msys64\usr\bin\pacman --noconfirm -Syyuu
          C:\tools\msys64\usr\bin\pacman --noconfirm -Syuu
      - name: Use Python Dependency Cache
        uses: actions/cache@v1.0.3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: |
          $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem"
          C:\tools\msys64\usr\bin\bash -lc "win-installer/msys2-install.sh"
        env:
          CHERE_INVOKING: yes
      - name: Create Windows Binaries
        run: |
          $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem"
          C:\tools\msys64\usr\bin\bash -lc "win-installer/msys2-build.sh"
        env:
          CHERE_INVOKING: yes
      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'win-installer/*.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  upload-macos:
    runs-on: macOS-latest
    env:
      PKG_CONFIG_PATH: /usr/local/Cellar/libffi/3.2.1/lib/pkgconfig:${PKG_CONFIG_PATH:-}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: brew install gobject-introspection gtk+3 adwaita-icon-theme
      - name: Install Poetry
        uses: danyeaw/install-poetry-action
        with:
          version: 1.0.0b3
      - name: Use Python Dependency Cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: Install Python Dependencies
        run: poetry install
      - name: Build Wheel and sdist
        run: poetry build
      - name: Create macOS Binary
        run: |
          cd macos-dmg
          ./package.sh
      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'macos-dmg/*dmg;dist/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
